@ECHO OFF

CALL %~dp0..\..\bin\date.bat
SET SQL_FOLDER=%~dp0%MY_YEAR%
SET SQL_FILE_NAME=%MY_YEAR%%MY_MONTH%%MY_DAY%.%COMPUTERNAME%.%USERNAME%.%MY_HOUR%%MY_MINUTE%%MY_SECOND%.%MY_MILLISECOND%.sql
SET SQL_FILE=%SQL_FOLDER%\%SQL_FILE_NAME%
ECHO %SQL_FILE%

IF NOT EXIST "%SQL_FOLDER%" MKDIR "%SQL_FOLDER%" || GOTO ERROR
ECHO. >"%SQL_FILE%" || GOTO ERROR
ECHO ALTER TABLE TODO >>"%SQL_FILE%" || GOTO ERROR
ECHO ADD COLUMN TODO, >>"%SQL_FILE%" || GOTO ERROR
ECHO ADD INDEX TODO >>"%SQL_FILE%" || GOTO ERROR
ECHO ; >>"%SQL_FILE%" || GOTO ERROR

REM Try to open file with editor

:END
ECHO File created: %MY_YEAR%\%SQL_FILE_NAME%
PAUSE
EXIT /B 0

:ERROR
ECHO [%DATE% %TIME%] ERROR: Can't create SQL file %SQL_FILE% ! >&2
PAUSE
EXIT /B 1
